# Copyright 2007 Wincent Colaiuta
# $Id$

module Walrus
  
  # Enumerable Tree class generated by a Parser instance.
  class Tree
    
    include Enumerable
    
    attr_accessor :template_superclass
    
    def each
      yield "something"
    end
    
  end # class Tree
end # module Walrus

